### ISSUE TITLE
Improve table lookup

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#1]
Looping over the entire table of regexes is quite expensive. I have an implementation at https://github.com/patxoca/z80count that groups regexes by mnemonic and only loops over a single group. It also adds tests (that need some cleanup, still not a Z80 programmer) and minor changes to make the code more pythonic.

Let me know if you are interested and want me to make a pull request.

**Comment by reidrac** [comment]
Sorry I missed this one!

Yes, please. Open a PR!

**Comment by reidrac** [comment]
Fixed by #2
