### ISSUE TITLE
Is ' -u' command line switch required?

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#10]
I'm wondering what's the intended use case for not specifying the `-u` switch.

https://github.com/reidrac/z80count/blob/b39f7395fe7b3db804b505c0dee353f228410dcd/z80count/z80count.py#L63-L69

When `update==False` it will keep the previous (and probably outdated) cycle counts in the comment, which makes little sense to me.

**Comment by reidrac** [comment]
I didn't want to replace existing comments. Sometimes I edit code that has already annotations.

We could change the default to make it on and have a flag to disable it. What do you think?

**Comment by patxoca** [comment]
I'm ok making the safest action the default. Keeping existing comments unmodified seems safer.

My point is that if I have:

```asm
ld d, a    ; [4 .. 93] my comment here
```

and rerun `z80count` without `-u` I get:

```asm
ld d, a    ; [4 .. 93] [4 .. 93] my comment here
```

which is a little weird. I'd expect the counts to be updated and the comment (the wordy part) kept (which already is).

When you say you have annotations you want to keep do you refer to `[a .. b]` or to actual comments (text, words)?

**Comment by reidrac** [comment]
In that way it helps me to compare different versions of the code by not updating the comment.

But you're right that it makes more sense to update it by default and use a flag to not update it when needed.
