### ISSUE TITLE
Provide a python package

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#3]
Although not strictly required it would be nice to have `z80count` packaged as a python distribution.

That would allow distribution via pypi and installation using standard python tools.

Let me know if you find that useful and I'll do a PR.

**Comment by reidrac** [comment]
I was planning to do it myself (specially now that pytest is a requirement), but PRs are welcome. Thanks!

**Comment by reidrac** [comment]
Fixed in #4
