### ISSUE TITLE
Add emacs (and other editors) support

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#5]
What are your thoughts about bundling editor support (emacs in my case) into the `z80count` distribution?

**Comment by reidrac** [comment]
Sounds like a good idea. The way it works now is basically a filter (stdin -> stdout). Not sure what it needs to be used from emacs, but go for it if it is useful to you.

**Comment by patxoca** [comment]
Sorry my question was not very clear (I don't feel comfortable writing in English). I meant adding the actual plugins to the distribution.

Acting as a filter is ok for emacs and probably all editors.

**Comment by reidrac** [comment]
I can't maintain plugins so it all depends if you want to do it.

**Comment by patxoca** [comment]
I can maintain the emacs plugin.

Alternatively, adding an `Editor support` section in the README linking to external plugins would achieve a similar result.
