### ISSUE TITLE
Bug accumulating cycles?

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#8]
My understanding is that the `cycles` attribute stores a pair `cycles if condition met / cycles if condition not met`.

On:

https://github.com/reidrac/z80count/blob/1737cac3f5fda65b1f39a417980353da12599d84/z80count/z80count.py#L41-L43

`total` is update and then used in updating `total_cond`, the final result is that the variable `total_cond` has both *condition met* and *condition not met* cycle count added.

In order to avoid that we can change the order:

```python
total_cond += total + int(c[0])
total += int(c[1])
```

OTOH, incrementing `total_cond` seems wrong to me, for similar reasons. I think it should be:

```python
total_cond = total + int(c[0])
total += int(c[1])
```

**Comment by reidrac** [comment]
You're absolutely right! It's even wrong in the README example:
```asm
and 7				; [7 .. 78]
jr z, no_fade_all_ink		; [12/7 .. 97/85]
```

Should be ```90/85```.

PRs are welcome; your fix sounds OK (+ the README example needs updating). The gif is wrong too, of course. I'll regenerate it when I have few minutes to spare.

Thanks for your help!

**Comment by patxoca** [comment]
My pleasure. I've enjoyed very much playing your games. It's nice to be able to give something  back.
